# Generated by Django 6.1.1 on 2026-09-09 08:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100, unique=True)),
                ('provider_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='OPERATIONAL', max_length=20)),
                ('last_sync', models.DateTimeField(default=django.utils.timezone.now)),
                ('records_count', models.IntegerField(default=0)),
                ('is_live_telemetry', models.BooleanField(default=False)),
                ('freshness_seconds', models.IntegerField(default=30)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('route_number', models.CharField(db_index=True, max_length=50)),
                ('route_name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('METRO', 'Ahmedabad Metro (GMRC)'), ('BRTS', 'Janmarg BRTS'), ('AMTS', 'AMTS City Bus'), ('WALK', 'Pedestrian Walking')], db_index=True, max_length=20)),
                ('color', models.CharField(default='#2563EB', max_length=20)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('is_circular', models.BooleanField(default=False)),
                ('headway_peak_mins', models.IntegerField(default=6)),
                ('headway_offpeak_mins', models.IntegerField(default=12)),
                ('first_trip_time', models.CharField(default='06:20', max_length=10)),
                ('last_trip_time', models.CharField(default='22:00', max_length=10)),
                ('average_speed_kmh', models.FloatField(default=30.0)),
                ('reliability_score', models.FloatField(default=0.95)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['mode', 'route_number'],
            },
        ),
        migrations.CreateModel(
            name='TransportAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('helpline', models.CharField(blank=True, max_length=50)),
                ('fare_policy', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Transport Agencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TransportMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('METRO', 'Ahmedabad Metro (GMRC)'), ('BRTS', 'Janmarg BRTS'), ('AMTS', 'AMTS City Bus'), ('WALK', 'Pedestrian Walking')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(default='bus', max_length=50)),
                ('color', models.CharField(default='#2563EB', max_length=20)),
                ('average_speed_kmh', models.FloatField(default=25.0)),
                ('boarding_time_mins', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='DataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=20)),
                ('records_updated', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('details', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='transit.datasource')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_gu', models.CharField(blank=True, max_length=255)),
                ('name_hi', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('mode', models.CharField(choices=[('METRO', 'Ahmedabad Metro (GMRC)'), ('BRTS', 'Janmarg BRTS'), ('AMTS', 'AMTS City Bus'), ('WALK', 'Pedestrian Walking')], db_index=True, max_length=20)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('zone', models.CharField(blank=True, max_length=50)),
                ('is_interchange', models.BooleanField(db_index=True, default=False)),
                ('wheelchair_accessible', models.BooleanField(default=True)),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_escalator', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_restroom', models.BooleanField(default=False)),
                ('platform_info', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transit.transportagency')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning / Moderate Delay'), ('CRITICAL', 'Critical Disruption / Suspension')], default='WARNING', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('UPCOMING', 'Upcoming')], default='ACTIVE', max_length=20)),
                ('delay_impact_mins', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='transit.route')),
                ('affected_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='transit.stop')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='transit.transportagency')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transit.transportagency'),
        ),
        migrations.CreateModel(
            name='FareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('METRO', 'Ahmedabad Metro (GMRC)'), ('BRTS', 'Janmarg BRTS'), ('AMTS', 'AMTS City Bus'), ('WALK', 'Pedestrian Walking')], max_length=20)),
                ('base_fare', models.FloatField(default=5.0)),
                ('base_distance_km', models.FloatField(default=2.0)),
                ('per_km_rate', models.FloatField(default=1.5)),
                ('max_fare', models.FloatField(default=30.0)),
                ('fare_brackets', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_rules', to='transit.transportagency')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('registration', models.CharField(blank=True, max_length=50)),
                ('mode', models.CharField(choices=[('METRO', 'Ahmedabad Metro (GMRC)'), ('BRTS', 'Janmarg BRTS'), ('AMTS', 'AMTS City Bus'), ('WALK', 'Pedestrian Walking')], max_length=20)),
                ('capacity', models.IntegerField(default=60)),
                ('is_electric', models.BooleanField(default=True)),
                ('is_wheelchair_accessible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='transit.transportagency')),
                ('current_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='transit.route')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed_kmh', models.FloatField(default=28.0)),
                ('heading', models.FloatField(default=0.0)),
                ('current_location_name', models.CharField(default='Ashram Road', max_length=255)),
                ('eta_next_stop_seconds', models.IntegerField(default=180)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ON_TIME', 'On Time'), ('SLIGHT_DELAY', 'Slight Delay (+1-4m)'), ('DELAYED', 'Delayed (+5m+)'), ('AHEAD', 'Ahead of Schedule'), ('DISRUPTED', 'Disrupted')], default='ON_TIME', max_length=20)),
                ('is_live', models.BooleanField(default=False)),
                ('data_source', models.CharField(default='DEMO_SIMULATION', max_length=50)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approaching_vehicles', to='transit.stop')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_position', to='transit.vehicle')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('distance_from_start_km', models.FloatField(default=0.0)),
                ('travel_time_mins', models.FloatField(default=2.0)),
                ('is_major_stop', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='transit.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='transit.stop')),
            ],
            options={
                'ordering': ['route', 'sequence'],
                'indexes': [models.Index(fields=['route', 'stop'], name='transit_rou_route_i_b5e777_idx')],
                'unique_together': {('route', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='PlaceLandmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_gu', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('RAILWAY_STATION', 'Railway Station'), ('AIRPORT', 'Airport Terminal'), ('METRO_STATION', 'Metro Station'), ('BRTS_HUB', 'BRTS Terminal / Hub'), ('EDUCATION', 'University / College'), ('COMMERCIAL', 'Commercial / Tech Park'), ('HOSPITAL', 'Hospital / Medical'), ('TOURIST', 'Tourist Landmark / Garden'), ('RESIDENTIAL', 'Residential Suburb')], default='COMMERCIAL', max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_popular', models.BooleanField(default=False)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('nearest_brts_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landmarks_brts', to='transit.stop')),
                ('nearest_metro_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landmarks_metro', to='transit.stop')),
            ],
            options={
                'ordering': ['-is_popular', 'name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='transit_pla_latitud_c60728_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('METRO_INTERCHANGE', 'Metro to Metro (Platform/Concourse)'), ('METRO_BRTS', 'Metro to BRTS Walking Transfer'), ('METRO_AMTS', 'Metro to AMTS Walking Transfer'), ('BRTS_AMTS', 'BRTS to AMTS Walking Transfer'), ('BRTS_BRTS', 'BRTS Corridor Transfer'), ('RAIL_TRANSIT', 'Indian Railways to Urban Transit'), ('PEDESTRIAN_LINK', 'Pedestrian Walkway')], default='PEDESTRIAN_LINK', max_length=30)),
                ('walking_distance_m', models.IntegerField(default=150)),
                ('walking_time_mins', models.FloatField(default=3.0)),
                ('transfer_penalty_mins', models.FloatField(default=2.0)),
                ('instructions', models.TextField(blank=True)),
                ('is_step_free', models.BooleanField(default=True)),
                ('is_sheltered', models.BooleanField(default=True)),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='transit.stop')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='transit.stop')),
            ],
            options={
                'unique_together': {('from_stop', 'to_stop')},
            },
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['latitude', 'longitude'], name='transit_sto_latitud_7b5245_idx'),
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['mode', 'is_interchange'], name='transit_sto_mode_d1f028_idx'),
        ),
    ]
