# Generated by Django 6.1.1 on 2026-09-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placelandmark',
            name='city',
            field=models.CharField(choices=[('AHMEDABAD', 'Ahmedabad'), ('GANDHINAGAR', 'Gandhinagar'), ('GIFT_CITY', 'GIFT City')], db_index=True, default='AHMEDABAD', max_length=50),
        ),
        migrations.AddField(
            model_name='stop',
            name='city',
            field=models.CharField(choices=[('AHMEDABAD', 'Ahmedabad'), ('GANDHINAGAR', 'Gandhinagar'), ('GIFT_CITY', 'GIFT City')], db_index=True, default='AHMEDABAD', max_length=50),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_platform',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transfer',
            name='stand_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_platform',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_buffer_mins',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='farerule',
            name='mode',
            field=models.CharField(choices=[('METRO', 'Ahmedabad/Gandhinagar Metro (GMRC)'), ('BRTS', 'Janmarg BRTS'), ('AMTS', 'AMTS City Bus'), ('RAIL', 'Indian Railways Intercity'), ('BUS', 'Gandhinagar Bus / GIFT Shuttle / GSRTC'), ('WALK', 'Pedestrian Walking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='placelandmark',
            name='category',
            field=models.CharField(choices=[('RAILWAY_STATION', 'Railway Station'), ('AIRPORT', 'Airport Terminal'), ('METRO_STATION', 'Metro Station'), ('BRTS_HUB', 'BRTS Terminal / Hub'), ('EDUCATION', 'University / College'), ('COMMERCIAL', 'Commercial / Tech Park'), ('HOSPITAL', 'Hospital / Medical'), ('GOVERNMENT', 'Government / Secretariat / Bhavan'), ('TOURIST', 'Tourist Landmark / Temple'), ('RESIDENTIAL', 'Residential Suburb / Sector')], default='COMMERCIAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='route',
            name='mode',
            field=models.CharField(choices=[('METRO', 'Ahmedabad/Gandhinagar Metro (GMRC)'), ('BRTS', 'Janmarg BRTS'), ('AMTS', 'AMTS City Bus'), ('RAIL', 'Indian Railways Intercity'), ('BUS', 'Gandhinagar Bus / GIFT Shuttle / GSRTC'), ('WALK', 'Pedestrian Walking')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stop',
            name='mode',
            field=models.CharField(choices=[('METRO', 'Ahmedabad/Gandhinagar Metro (GMRC)'), ('BRTS', 'Janmarg BRTS'), ('AMTS', 'AMTS City Bus'), ('RAIL', 'Indian Railways Intercity'), ('BUS', 'Gandhinagar Bus / GIFT Shuttle / GSRTC'), ('WALK', 'Pedestrian Walking')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('METRO_INTERCHANGE', 'Metro to Metro (Platform/Concourse)'), ('METRO_BRTS', 'Metro to BRTS Walking Transfer'), ('METRO_AMTS', 'Metro to AMTS Walking Transfer'), ('BRTS_AMTS', 'BRTS to AMTS Walking Transfer'), ('BRTS_BRTS', 'BRTS Corridor Transfer'), ('RAIL_TRANSIT', 'Indian Railways to Urban Transit'), ('METRO_SHUTTLE', 'Metro to Gandhinagar/GIFT Shuttle'), ('PEDESTRIAN_LINK', 'Pedestrian Walkway')], default='PEDESTRIAN_LINK', max_length=30),
        ),
        migrations.AlterField(
            model_name='transportmode',
            name='code',
            field=models.CharField(choices=[('METRO', 'Ahmedabad/Gandhinagar Metro (GMRC)'), ('BRTS', 'Janmarg BRTS'), ('AMTS', 'AMTS City Bus'), ('RAIL', 'Indian Railways Intercity'), ('BUS', 'Gandhinagar Bus / GIFT Shuttle / GSRTC'), ('WALK', 'Pedestrian Walking')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mode',
            field=models.CharField(choices=[('METRO', 'Ahmedabad/Gandhinagar Metro (GMRC)'), ('BRTS', 'Janmarg BRTS'), ('AMTS', 'AMTS City Bus'), ('RAIL', 'Indian Railways Intercity'), ('BUS', 'Gandhinagar Bus / GIFT Shuttle / GSRTC'), ('WALK', 'Pedestrian Walking')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='placelandmark',
            index=models.Index(fields=['city', 'category'], name='transit_pla_city_6a76ff_idx'),
        ),
    ]
