# Generated by Django 6.1.1 on 2026-09-10 14:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0002_placelandmark_city_stop_city_transfer_from_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('service_id', models.CharField(default='DAILY', max_length=50)),
                ('headsign', models.CharField(blank=True, max_length=255)),
                ('direction', models.IntegerField(default=0)),
                ('departure_time_start', models.CharField(max_length=10)),
                ('arrival_time_end', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['departure_time_start'],
            },
        ),
        migrations.CreateModel(
            name='TripStopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_sequence', models.IntegerField()),
                ('arrival_time', models.CharField(max_length=10)),
                ('departure_time', models.CharField(max_length=10)),
                ('pickup_type', models.IntegerField(default=0)),
                ('drop_off_type', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['trip', 'stop_sequence'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='fleet_active',
            field=models.IntegerField(default=0, help_text='Buses currently active in service'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='fleet_deployed',
            field=models.IntegerField(default=0, help_text='Fleet deployed on ground'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='fleet_total',
            field=models.IntegerField(default=0, help_text='Total sanctioned fleet allocation'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_updated_feed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='datasynclog',
            name='errors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datasynclog',
            name='records_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='placelandmark',
            name='nearest_electric_bus_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landmarks_electric_bus', to='transit.stop'),
        ),
        migrations.AddField(
            model_name='route',
            name='is_electric',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='servicealert',
            name='alert_type',
            field=models.CharField(choices=[('ROUTE_DISRUPTION', 'Route Disruption'), ('VEHICLE_BREAKDOWN', 'Vehicle Breakdown'), ('TRAFFIC_DELAY', 'Traffic Delay'), ('TEMPORARY_CLOSURE', 'Temporary Road/Station Closure'), ('ROUTE_DIVERSION', 'Route Diversion'), ('CHARGING_DEPOT_ISSUE', 'Charging / Depot Issue'), ('WEATHER_DISRUPTION', 'Weather Disruption'), ('GENERAL_NOTICE', 'General Notice')], default='GENERAL_NOTICE', max_length=30),
        ),
        migrations.AddField(
            model_name='servicealert',
            name='alternative_advice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='accessible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='air_conditioned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='battery_status',
            field=models.IntegerField(blank=True, help_text='Battery state of charge 0-100%', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='charging_status',
            field=models.CharField(choices=[('CHARGING', 'Charging at Depot Hub'), ('DISCHARGING', 'In Service / Active Discharging'), ('STANDBY', 'Standby at Terminal'), ('OFFLINE', 'Depot Standby / Offline')], default='DISCHARGING', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fleet_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='operator',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_capacity',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('9M_ELECTRIC_AC', '9m Low-Floor AC Electric Bus (PM-eBus Sewa)'), ('12M_ELECTRIC_AC', '12m Low-Floor AC Electric Bus'), ('GIFT_AUTONOMOUS_EV', 'GIFT City Autonomous EV Shuttle'), ('METRO_RAKE', 'GMRC 3-Car Metro Train Rake'), ('BRTS_BUS', 'Janmarg Euro-VI / EV Bus'), ('AMTS_BUS', 'AMTS Midi/Standard City Bus'), ('RAIL_TRAIN', 'Indian Railways Intercity/MEMU Train')], default='9M_ELECTRIC_AC', max_length=30),
        ),
        migrations.AddField(
            model_name='vehicleposition',
            name='telemetry_type',
            field=models.CharField(choices=[('REAL_TIME', 'Live GPS Feed'), ('ESTIMATED', 'Estimated / Projected'), ('SCHEDULED', 'Scheduled Timetable'), ('UNKNOWN', 'Telemetry Unknown')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='farerule',
            name='mode',
            field=models.CharField(choices=[('METRO', 'Ahmedabad/Gandhinagar Metro (GMRC)'), ('BRTS', 'Janmarg BRTS'), ('AMTS', 'AMTS City Bus'), ('GANDHINAGAR_ELECTRIC_BUS', 'Gandhinagar Electric Bus (GGTSL)'), ('RAIL', 'Indian Railways Intercity'), ('BUS', 'GIFT Shuttle / Regional Bus / GSRTC'), ('WALK', 'Pedestrian Walking')], max_length=30),
        ),
        migrations.AlterField(
            model_name='placelandmark',
            name='category',
            field=models.CharField(choices=[('RAILWAY_STATION', 'Railway Station'), ('AIRPORT', 'Airport Terminal'), ('METRO_STATION', 'Metro Station'), ('BRTS_HUB', 'BRTS Terminal / Hub'), ('ELECTRIC_BUS_HUB', 'Electric Bus Terminal / Depot'), ('EDUCATION', 'University / College'), ('COMMERCIAL', 'Commercial / Tech Park'), ('HOSPITAL', 'Hospital / Medical'), ('GOVERNMENT', 'Government / Secretariat / Bhavan'), ('TOURIST', 'Tourist Landmark / Temple'), ('RESIDENTIAL', 'Residential Suburb / Sector')], default='COMMERCIAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='route',
            name='mode',
            field=models.CharField(choices=[('METRO', 'Ahmedabad/Gandhinagar Metro (GMRC)'), ('BRTS', 'Janmarg BRTS'), ('AMTS', 'AMTS City Bus'), ('GANDHINAGAR_ELECTRIC_BUS', 'Gandhinagar Electric Bus (GGTSL)'), ('RAIL', 'Indian Railways Intercity'), ('BUS', 'GIFT Shuttle / Regional Bus / GSRTC'), ('WALK', 'Pedestrian Walking')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='stop',
            name='mode',
            field=models.CharField(choices=[('METRO', 'Ahmedabad/Gandhinagar Metro (GMRC)'), ('BRTS', 'Janmarg BRTS'), ('AMTS', 'AMTS City Bus'), ('GANDHINAGAR_ELECTRIC_BUS', 'Gandhinagar Electric Bus (GGTSL)'), ('RAIL', 'Indian Railways Intercity'), ('BUS', 'GIFT Shuttle / Regional Bus / GSRTC'), ('WALK', 'Pedestrian Walking')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('METRO_INTERCHANGE', 'Metro to Metro (Platform/Concourse)'), ('METRO_BRTS', 'Metro to BRTS Walking Transfer'), ('METRO_AMTS', 'Metro to AMTS Walking Transfer'), ('METRO_ELECTRIC_BUS', 'Metro to Gandhinagar Electric Bus Transfer'), ('BRTS_AMTS', 'BRTS to AMTS Walking Transfer'), ('BRTS_BRTS', 'BRTS Corridor Transfer'), ('BRTS_ELECTRIC_BUS', 'BRTS to Gandhinagar Electric Bus Transfer'), ('AMTS_ELECTRIC_BUS', 'AMTS to Gandhinagar Electric Bus Transfer'), ('ELECTRIC_BUS_ELECTRIC_BUS', 'Gandhinagar Electric Bus Corridor Transfer'), ('RAIL_TRANSIT', 'Indian Railways to Urban Transit'), ('METRO_SHUTTLE', 'Metro to Gandhinagar/GIFT Shuttle'), ('GIFT_SHUTTLE_TRANSFER', 'GIFT City Multimodal Concourse Transfer'), ('PEDESTRIAN_LINK', 'Pedestrian Walkway')], default='PEDESTRIAN_LINK', max_length=35),
        ),
        migrations.AlterField(
            model_name='transportmode',
            name='code',
            field=models.CharField(choices=[('METRO', 'Ahmedabad/Gandhinagar Metro (GMRC)'), ('BRTS', 'Janmarg BRTS'), ('AMTS', 'AMTS City Bus'), ('GANDHINAGAR_ELECTRIC_BUS', 'Gandhinagar Electric Bus (GGTSL)'), ('RAIL', 'Indian Railways Intercity'), ('BUS', 'GIFT Shuttle / Regional Bus / GSRTC'), ('WALK', 'Pedestrian Walking')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_electric',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mode',
            field=models.CharField(choices=[('METRO', 'Ahmedabad/Gandhinagar Metro (GMRC)'), ('BRTS', 'Janmarg BRTS'), ('AMTS', 'AMTS City Bus'), ('GANDHINAGAR_ELECTRIC_BUS', 'Gandhinagar Electric Bus (GGTSL)'), ('RAIL', 'Indian Railways Intercity'), ('BUS', 'GIFT Shuttle / Regional Bus / GSRTC'), ('WALK', 'Pedestrian Walking')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicleposition',
            name='last_updated',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vehicleposition',
            name='latitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vehicleposition',
            name='longitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='datasynclog',
            index=models.Index(fields=['timestamp'], name='transit_dat_timesta_69b12a_idx'),
        ),
        migrations.AddIndex(
            model_name='datasynclog',
            index=models.Index(fields=['status'], name='transit_dat_status_dc1ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['mode', 'is_active'], name='transit_rou_mode_203cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['is_electric'], name='transit_rou_is_elec_e569d0_idx'),
        ),
        migrations.AddIndex(
            model_name='servicealert',
            index=models.Index(fields=['status', 'severity'], name='transit_ser_status_8a7762_idx'),
        ),
        migrations.AddIndex(
            model_name='servicealert',
            index=models.Index(fields=['valid_from'], name='transit_ser_valid_f_8c325d_idx'),
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['city', 'mode'], name='transit_sto_city_a20515_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['mode', 'is_electric'], name='transit_veh_mode_48f51f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['agency', 'is_active'], name='transit_veh_agency__05df6d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleposition',
            index=models.Index(fields=['latitude', 'longitude'], name='transit_veh_latitud_73815a_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleposition',
            index=models.Index(fields=['last_updated'], name='transit_veh_last_up_35fbcd_idx'),
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='transit.route'),
        ),
        migrations.AddField(
            model_name='tripstoptime',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stop_times', to='transit.stop'),
        ),
        migrations.AddField(
            model_name='tripstoptime',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='transit.trip'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route', 'service_id'], name='transit_tri_route_i_333ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['departure_time_start'], name='transit_tri_departu_4c33cd_idx'),
        ),
        migrations.AddIndex(
            model_name='tripstoptime',
            index=models.Index(fields=['stop', 'departure_time'], name='transit_tri_stop_id_77b05b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tripstoptime',
            unique_together={('trip', 'stop_sequence')},
        ),
    ]
