# Generated by Django 6.1.1 on 2026-09-08 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, unique=True)),
                ('total_buses', models.IntegerField(default=0)),
                ('total_detections', models.IntegerField(default=0)),
                ('road_hazards', models.IntegerField(default=0)),
                ('traffic_events', models.IntegerField(default=0)),
                ('incidents', models.IntegerField(default=0)),
                ('critical_incidents', models.IntegerField(default=0)),
                ('average_confidence', models.FloatField(default=94.5)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
    ]
