# Generated by Django 6.1.1 on 2026-09-08 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('CRITICAL', 'Critical Alert')], db_index=True, default='MEDIUM', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('latitude', models.FloatField(default=23.0225)),
                ('longitude', models.FloatField(default=72.5714)),
                ('confidence', models.FloatField(default=0.95)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='fleet.bus')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', 'is_read', '-created_at'], name='notificatio_severit_5f77e4_idx')],
            },
        ),
    ]
