# Generated by Django 6.1.1 on 2026-09-08 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('vehicle_type', models.CharField(default='SUV / Car', max_length=50)),
                ('vehicle_color', models.CharField(default='White', max_length=50)),
                ('confidence', models.FloatField(default=0.95)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('flagged_for_incident', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='ANPRDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=50)),
                ('confidence', models.FloatField(default=0.964)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('image_reference', models.CharField(blank=True, max_length=500, null=True)),
                ('location_name', models.CharField(default='Ahmedabad', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anpr_scans', to='fleet.bus')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anpr_records', to='vehicles.trackedvehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('direction', models.CharField(default='Northbound', max_length=50)),
                ('speed_estimate', models.FloatField(default=45.0)),
                ('confidence', models.FloatField(default=0.92)),
                ('frame_reference', models.CharField(blank=True, max_length=500, null=True)),
                ('location_name', models.CharField(default='Ahmedabad Road', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_sightings', to='fleet.bus')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='vehicles.trackedvehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
