# Generated by Django 6.1.1 on 2026-09-08 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=255)),
                ('segment_code', models.CharField(max_length=50, unique=True)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('condition_score', models.FloatField(default=75.0, help_text='Score 0 (worst) to 100 (best)')),
                ('is_critical', models.BooleanField(db_index=True, default=False)),
                ('last_surveyed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RoadHazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(db_index=True, max_length=255)),
                ('hazard_type', models.CharField(choices=[('POTHOLE', 'Pothole'), ('ROAD_DAMAGE', 'Road Surface Damage'), ('WATERLOGGING', 'Waterlogging'), ('MISSING_DIVIDER', 'Missing Lane Divider'), ('MISSING_ZEBRA_CROSSING', 'Missing Zebra Crossing'), ('UNMARKED_SPEEDBUMP', 'Unmarked Speed Bump')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=20)),
                ('confidence', models.FloatField(default=0.9)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('first_detected', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_detected', models.DateTimeField(default=django.utils.timezone.now)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Inspection'), ('VERIFIED', 'Verified'), ('IN_PROGRESS', 'Repair In Progress'), ('RESOLVED', 'Resolved')], db_index=True, default='PENDING', max_length=30)),
                ('maintenance_priority', models.IntegerField(default=50, help_text='Priority score 1-100')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_by_bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_hazards', to='fleet.bus')),
            ],
            options={
                'ordering': ['-maintenance_priority', '-last_detected'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(max_length=50, unique=True)),
                ('assigned_team', models.CharField(default='Ahmedabad Municipal Corporation PWD', max_length=150)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roads.roadhazard')),
            ],
        ),
        migrations.AddIndex(
            model_name='roadhazard',
            index=models.Index(fields=['road_name', 'hazard_type'], name='roads_roadh_road_na_4feb17_idx'),
        ),
        migrations.AddIndex(
            model_name='roadhazard',
            index=models.Index(fields=['severity', 'status'], name='roads_roadh_severit_52d39b_idx'),
        ),
    ]
