# Generated by Django 6.1.1 on 2026-09-08 15:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('incident_type', models.CharField(choices=[('HIT_AND_RUN', 'Hit and Run'), ('RASH_DRIVING', 'Rash Driving'), ('PEDESTRIAN_RISK', 'Pedestrian Risk'), ('ACCIDENT', 'Traffic Accident'), ('ROAD_HAZARD', 'Critical Road Hazard'), ('WATERLOGGING', 'Severe Waterlogging'), ('OTHER', 'Other Urban Safety Incident')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='HIGH', max_length=20)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('confidence', models.FloatField(default=0.95)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('ASSIGNED', 'Assigned'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], db_index=True, default='OPEN', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('assigned_team', models.CharField(default='Ahmedabad Traffic Police QRT', max_length=150)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('vehicle_info', models.JSONField(blank=True, default=dict)),
                ('evidence_frame', models.CharField(blank=True, max_length=500, null=True)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='fleet.bus')),
                ('tracked_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='vehicles.trackedvehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['incident_type', '-timestamp'], name='incidents_i_inciden_0fd628_idx'), models.Index(fields=['severity', 'status'], name='incidents_i_severit_1a089f_idx')],
            },
        ),
    ]
