# Generated by Django 6.1.1 on 2026-09-08 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('detection_type', models.CharField(choices=[('POTHOLE', 'Pothole'), ('ROAD_DAMAGE', 'Road Damage'), ('WATERLOGGING', 'Waterlogging'), ('MISSING_DIVIDER', 'Missing Divider'), ('MISSING_ZEBRA_CROSSING', 'Missing Zebra Crossing'), ('TRAFFIC_SIGN', 'Traffic Sign Issue'), ('VEHICLE', 'Vehicle'), ('PEDESTRIAN', 'Pedestrian'), ('SCHOOL_CHILD', 'School Child Risk'), ('RASH_DRIVING', 'Rash Driving'), ('HIT_AND_RUN', 'Hit and Run')], db_index=True, max_length=50)),
                ('confidence', models.FloatField(db_index=True, help_text='Confidence between 0.0 and 1.0')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=20)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('frame_reference', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('VERIFIED', 'Verified'), ('DISMISSED', 'Dismissed'), ('PROCESSED', 'Processed into Hazard/Incident')], db_index=True, default='NEW', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('location_name', models.CharField(blank=True, default='Ahmedabad Road', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='fleet.bus')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['detection_type', '-timestamp'], name='detections__detecti_a9046c_idx'), models.Index(fields=['bus', '-timestamp'], name='detections__bus_id_2221fa_idx')],
            },
        ),
    ]
