# Generated by Django 6.1.1 on 2026-09-08 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('route_name', models.CharField(max_length=255)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DIVERTED', 'Diverted')], default='ACTIVE', max_length=20)),
                ('waypoints', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['route_number'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('PROCESSING', 'Processing'), ('MAINTENANCE', 'Maintenance')], db_index=True, default='ONLINE', max_length=20)),
                ('latitude', models.FloatField(db_index=True, default=23.0225)),
                ('longitude', models.FloatField(db_index=True, default=72.5714)),
                ('speed', models.FloatField(default=0.0)),
                ('heading', models.FloatField(default=0.0)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('ai_status', models.CharField(default='Processing', max_length=50)),
                ('current_location_name', models.CharField(blank=True, default='SG Highway', max_length=255)),
                ('cameras_status', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='fleet.busroute')),
            ],
            options={
                'verbose_name_plural': 'Buses',
                'ordering': ['bus_id'],
            },
        ),
        migrations.CreateModel(
            name='BusCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=100)),
                ('camera_type', models.CharField(choices=[('FRONT', 'Front Road Sensing'), ('REAR', 'Rear Traffic Sensing'), ('LEFT', 'Left Pavement/Lane'), ('RIGHT', 'Right Traffic/Lane'), ('PASSENGER', 'Passenger Cabin')], default='FRONT', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ERROR', 'Error')], default='ACTIVE', max_length=20)),
                ('last_frame', models.CharField(blank=True, max_length=500, null=True)),
                ('resolution', models.CharField(default='1920x1080', max_length=50)),
                ('fps', models.IntegerField(default=30)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='fleet.bus')),
            ],
            options={
                'ordering': ['bus', 'camera_type'],
                'unique_together': {('bus', 'camera_type')},
            },
        ),
        migrations.CreateModel(
            name='BusLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0.0)),
                ('heading', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='fleet.bus')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['bus', '-timestamp'], name='fleet_buslo_bus_id_2ce30b_idx')],
            },
        ),
    ]
