from typing import List, Dict, Any
from .base import TransportProviderBase

class MetroProvider(TransportProviderBase):
    """
    Official GMRC (Gujarat Metro Rail Corporation) Ahmedabad & Gandhinagar Metro Network Provider.
    Covers:
    - Blue Line (East-West Corridor): Thaltej Gam ↔ Vastral Gam
    - Red Line (North-South Corridor + Phase 2 Extension): APMC ↔ Motera Stadium ↔ GNLU ↔ Mahatma Mandir
    - GIFT City Branch: GNLU Interchange ↔ PDEU (PDPU) ↔ GIFT City FinTech Hub
    - Major Interchanges: Old High Court (Blue/Red), GNLU (Red/GIFT Branch), Sabarmati (Rail/Metro)
    """

    def get_agency_info(self) -> Dict[str, Any]:
        return {
            'code': 'GMRC',
            'name': 'Ahmedabad & Gandhinagar Metro',
            'full_name': 'Gujarat Metro Rail Corporation Limited',
            'website': 'https://www.gujaratmetrorail.com',
            'helpline': '1800-300-1111',
            'fare_policy': 'Distance based: ₹5 (0-2.5 km), ₹10 (2.5-7.5 km), ₹15 (7.5-12.5 km), ₹20 (12.5-17.5 km), ₹25 (17.5-25 km), ₹30 (25-35 km), ₹35 (35+ km)',
        }

    def get_stops(self) -> List[Dict[str, Any]]:
        return [
            # --- Blue Line (East-West Corridor): Thaltej Gam -> Vastral Gam ---
            {
                'stop_id': 'METRO-EW-01',
                'name': 'Thaltej Gam',
                'name_gu': 'થલતેજ ગામ',
                'name_hi': 'थलतेज गाँव',
                'code': 'TGAM',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0560,
                'longitude': 72.5020,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2 (Elevated)',
            },
            {
                'stop_id': 'METRO-EW-02',
                'name': 'Thaltej Metro',
                'name_gu': 'થલતેજ',
                'name_hi': 'थलतेज',
                'code': 'THAL',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0525,
                'longitude': 72.5165,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 (Toward Vastral) / 2 (Toward Thaltej Gam)',
            },
            {
                'stop_id': 'METRO-EW-03',
                'name': 'Doordarshan Kendra',
                'name_gu': 'દૂરદર્શન કેન્દ્ર',
                'name_hi': 'दूरदर्शन केंद्र',
                'code': 'DDKN',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0489,
                'longitude': 72.5298,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-EW-04',
                'name': 'Gurukul Road',
                'name_gu': 'ગુરુકુળ રોડ',
                'name_hi': 'गुरुकुल रोड',
                'code': 'GUKL',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0442,
                'longitude': 72.5385,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-EW-05',
                'name': 'Gujarat University',
                'name_gu': 'ગુજરાત યુનિવર્સિટી',
                'name_hi': 'गुजरात विश्वविद्यालय',
                'code': 'GUUN',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0381,
                'longitude': 72.5482,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-EW-06',
                'name': 'Commerce Six Road',
                'name_gu': 'કોમર્સ છ રસ્તા',
                'name_hi': 'कॉमर्स सिक्स रोड',
                'code': 'CSXR',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0375,
                'longitude': 72.5562,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-EW-07',
                'name': 'SP Stadium',
                'name_gu': 'સરદાર પટેલ સ્ટેડિયમ',
                'name_hi': 'सरदार पटेल स्टेडियम',
                'code': 'SPST',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0398,
                'longitude': 72.5645,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-INT-01',
                'name': 'Old High Court (Interchange)',
                'name_gu': 'જૂની હાઇકોર્ટ (ઇન્ટરચેન્જ)',
                'name_hi': 'पुरानी उच्च न्यायालय (इंटरचेंज)',
                'code': 'OHCT',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0401,
                'longitude': 72.5709,
                'is_interchange': True,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Level 1: Blue Line (East-West) | Level 2: Red Line (North-South)',
            },
            {
                'stop_id': 'METRO-EW-08',
                'name': 'Sabarmati Riverfront',
                'name_gu': 'સાબરમતી રિવરફ્રન્ટ',
                'name_hi': 'साबरमती रिवरफ्रंट',
                'code': 'SBRF',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0345,
                'longitude': 72.5780,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-EW-09',
                'name': 'Shahpur',
                'name_gu': 'શાહપુર',
                'name_hi': 'शाहपुर',
                'code': 'SHHP',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0360,
                'longitude': 72.5835,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Underground Concourse (Platform 1 & 2)',
            },
            {
                'stop_id': 'METRO-EW-10',
                'name': 'Gheekanta',
                'name_gu': 'ઘીકાંટા',
                'name_hi': 'घीकांटा',
                'code': 'GHKN',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0290,
                'longitude': 72.5880,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Underground Concourse (Platform 1 & 2)',
            },
            {
                'stop_id': 'METRO-EW-11',
                'name': 'Kalupur Railway Station Metro',
                'name_gu': 'કાલુપુર રેલ્વે સ્ટેશન મેટ્રો',
                'name_hi': 'कालुपुर रेलवे स्टेशन मेट्रो',
                'code': 'KLPR',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0245,
                'longitude': 72.6000,
                'is_interchange': True,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Underground (Direct connection to Ahmedabad Main Railway Station Platform 1)',
            },
            {
                'stop_id': 'METRO-EW-12',
                'name': 'Kankaria East',
                'name_gu': 'કાંકરિયા પૂર્વ',
                'name_hi': 'कांकरिया पूर्व',
                'code': 'KKRE',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0120,
                'longitude': 72.6075,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-EW-13',
                'name': 'Apparel Park',
                'name_gu': 'એપરલ પાર્ક',
                'name_hi': 'अपैरल पार्क',
                'code': 'APRP',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0075,
                'longitude': 72.6210,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2 (Depot connection)',
            },
            {
                'stop_id': 'METRO-EW-14',
                'name': 'Amraiwadi',
                'name_gu': 'અમરાઇવાડી',
                'name_hi': 'अमराईवाड़ी',
                'code': 'AMRW',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0040,
                'longitude': 72.6325,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-EW-15',
                'name': 'Rabari Colony',
                'name_gu': 'રબારી કોલોની',
                'name_hi': 'रबारी कॉलोनी',
                'code': 'RBCN',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0020,
                'longitude': 72.6450,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-EW-16',
                'name': 'Vastral',
                'name_gu': 'વસ્ત્રાલ',
                'name_hi': 'वस्त्राल',
                'code': 'VSTL',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0005,
                'longitude': 72.6560,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-EW-17',
                'name': 'Vastral Gam',
                'name_gu': 'વસ્ત્રાલ ગામ',
                'name_hi': 'વસ્ત્રાલ गाँव',
                'code': 'VGAM',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 22.9990,
                'longitude': 72.6680,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2 (Terminal)',
            },

            # --- Red Line (North-South Corridor Phase 1): Motera Stadium -> APMC ---
            {
                'stop_id': 'METRO-NS-01',
                'name': 'Motera Stadium Metro',
                'name_gu': 'મોટેરા સ્ટેડિયમ મેટ્રો',
                'name_hi': 'मोटेरा स्टेडियम मेट्रो',
                'code': 'MTRS',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0915,
                'longitude': 72.5975,
                'is_interchange': True,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2 (Phase 1/2 Interchange Node)',
            },
            {
                'stop_id': 'METRO-NS-02',
                'name': 'Sabarmati Railway Station Metro',
                'name_gu': 'સાબરમતી રેલ્વે સ્ટેશન મેટ્રો',
                'name_hi': 'સાબરમતી रेलवे स्टेशन मेट्रो',
                'code': 'SBMT',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0762,
                'longitude': 72.5855,
                'is_interchange': True,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 (Toward APMC) / Platform 2 (Toward Gandhinagar/Motera)',
            },
            {
                'stop_id': 'METRO-NS-03',
                'name': 'AEC (Ahmedabad Electricity Company)',
                'name_gu': 'એઇસી',
                'name_hi': 'एईसी',
                'code': 'AECC',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0695,
                'longitude': 72.5810,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-NS-04',
                'name': 'Sabarmati Metro',
                'name_gu': 'સાબરમતી',
                'name_hi': 'સાબરમતી',
                'code': 'SBMT2',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0610,
                'longitude': 72.5765,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-NS-05',
                'name': 'Ranip Metro',
                'name_gu': 'રાણીપ',
                'name_hi': 'राणीप',
                'code': 'RANI',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0545,
                'longitude': 72.5740,
                'is_interchange': True,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2 (Ranip GSRTC Bus Hub interchange)',
            },
            {
                'stop_id': 'METRO-NS-06',
                'name': 'Vadaj',
                'name_gu': 'વાડજ',
                'name_hi': 'वाडज',
                'code': 'VADJ',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0490,
                'longitude': 72.5725,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-NS-07',
                'name': 'Vijay Nagar',
                'name_gu': 'વિજય નગર',
                'name_hi': 'विजय नगर',
                'code': 'VJNR',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0440,
                'longitude': 72.5718,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-NS-08',
                'name': 'Usmanpura',
                'name_gu': 'ઉસ્માનપુરા',
                'name_hi': 'उस्मानपुरा',
                'code': 'USMN',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0365,
                'longitude': 72.5702,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-NS-09',
                'name': 'Gandhigram',
                'name_gu': 'ગાંધીગ્રામ',
                'name_hi': 'गांधीग्राम',
                'code': 'GGRAM',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0270,
                'longitude': 72.5710,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2 (Near Ashram Road)',
            },
            {
                'stop_id': 'METRO-NS-10',
                'name': 'Paldi',
                'name_gu': 'પાલડી',
                'name_hi': 'पालडी',
                'code': 'PALD',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0160,
                'longitude': 72.5695,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-NS-11',
                'name': 'Shreyas',
                'name_gu': 'શ્રેયસ',
                'name_hi': 'श्रेयस',
                'code': 'SHRY',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.0070,
                'longitude': 72.5640,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-NS-12',
                'name': 'Rajiv Nagar',
                'name_gu': 'રાજીવ નગર',
                'name_hi': 'राजीव नगर',
                'code': 'RJNR',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 22.9975,
                'longitude': 72.5580,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-NS-13',
                'name': 'Jivraj Park',
                'name_gu': 'જીવરાજ પાર્ક',
                'name_hi': 'जीवराज पार्क',
                'code': 'JVRJ',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 22.9910,
                'longitude': 72.5480,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-NS-14',
                'name': 'APMC Metro',
                'name_gu': 'એપીએમસી',
                'name_hi': 'एपीएमसी',
                'code': 'APMC',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 22.9830,
                'longitude': 72.5360,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2 (Terminal)',
            },

            # --- Red Line Phase 2 Extension (Motera -> Gandhinagar Mahatma Mandir) ---
            {
                'stop_id': 'METRO-NS-16',
                'name': 'Koteshwar Road',
                'name_gu': 'કોટેશ્વર રોડ',
                'name_hi': 'कोटेश्वर रोड',
                'code': 'KTSR',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.1070,
                'longitude': 72.5980,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-NS-17',
                'name': 'Vishwakarma College Metro Station',
                'name_gu': 'વિશ્વકર્મા કોલેજ મેટ્રો સ્ટેશન',
                'name_hi': 'विश्वकर्मा कॉलेज मेट्रो स्टेशन',
                'code': 'VKCL',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.1090,
                'longitude': 72.5950,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 (Toward APMC) / Platform 2 (Toward Gandhinagar Mahatma Mandir)',
            },
            {
                'stop_id': 'METRO-NS-18',
                'name': 'Tapovan Circle',
                'name_gu': 'તપોવન સર્કલ',
                'name_hi': 'तपोवन सर्कल',
                'code': 'TPVN',
                'city': 'AHMEDABAD',
                'mode': 'METRO',
                'latitude': 23.1290,
                'longitude': 72.5950,
                'is_interchange': True,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2 (Interchange with BRTS/GIFT Shuttles)',
            },
            {
                'stop_id': 'METRO-NS-19',
                'name': 'Narmada Canal',
                'name_gu': 'નર્મદા કેનાલ',
                'name_hi': 'नर्मदा नहर',
                'code': 'NRMD',
                'city': 'GANDHINAGAR',
                'mode': 'METRO',
                'latitude': 23.1410,
                'longitude': 72.5930,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-NS-20',
                'name': 'Koba Circle',
                'name_gu': 'કોબા સર્કલ',
                'name_hi': 'कोबा सर्कल',
                'code': 'KOBA',
                'city': 'GANDHINAGAR',
                'mode': 'METRO',
                'latitude': 23.1550,
                'longitude': 72.5900,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-NS-21',
                'name': 'Juna Koba',
                'name_gu': 'જુના કોબા',
                'name_hi': 'जूना कोबा',
                'code': 'JKOB',
                'city': 'GANDHINAGAR',
                'mode': 'METRO',
                'latitude': 23.1650,
                'longitude': 72.6200,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-NS-22',
                'name': 'Koba Gam',
                'name_gu': 'કોબા ગામ',
                'name_hi': 'કોબા ગામ',
                'code': 'KBGM',
                'city': 'GANDHINAGAR',
                'mode': 'METRO',
                'latitude': 23.1720,
                'longitude': 72.6300,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-INT-02',
                'name': 'GNLU (Gujarat National Law University Interchange)',
                'name_gu': 'જીએનએલયુ (ઇન્ટરચેન્જ)',
                'name_hi': 'जीएनएलयू (इंटरचेंज)',
                'code': 'GNLU',
                'city': 'GANDHINAGAR',
                'mode': 'METRO',
                'latitude': 23.1540,
                'longitude': 72.6500,
                'is_interchange': True,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2 (Red Line to Mahatma Mandir) | Platform 3 & 4 (GIFT City Branch)',
            },
            {
                'stop_id': 'METRO-GND-01',
                'name': 'Raysan',
                'name_gu': 'રાયસણ',
                'name_hi': 'रायसन',
                'code': 'RAYS',
                'city': 'GANDHINAGAR',
                'mode': 'METRO',
                'latitude': 23.1750,
                'longitude': 72.6410,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-GND-02',
                'name': 'Randesan',
                'name_gu': 'રાંદેસણ',
                'name_hi': 'रांदेसन',
                'code': 'RNDS',
                'city': 'GANDHINAGAR',
                'mode': 'METRO',
                'latitude': 23.1870,
                'longitude': 72.6370,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-GND-03',
                'name': 'Dholakuva Circle',
                'name_gu': 'ધોળાકુવા સર્કલ',
                'name_hi': 'धोलाकुवा सर्कल',
                'code': 'DHLK',
                'city': 'GANDHINAGAR',
                'mode': 'METRO',
                'latitude': 23.2087,
                'longitude': 72.6253,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-GND-04',
                'name': 'Infocity Metro',
                'name_gu': 'ઇન્ફોસિટી મેટ્રો',
                'name_hi': 'इन्फोसिटी मेट्रो',
                'code': 'INFO',
                'city': 'GANDHINAGAR',
                'mode': 'METRO',
                'latitude': 23.1965,
                'longitude': 72.6288,
                'is_interchange': True,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2 (Infocity IT Park & Gandhinagar Local Bus Hub)',
            },
            {
                'stop_id': 'METRO-GND-05',
                'name': 'Sector 1 Metro',
                'name_gu': 'સેક્ટર ૧ મેટ્રો',
                'name_hi': 'सेक्टर 1 मेट्रो',
                'code': 'SEC1',
                'city': 'GANDHINAGAR',
                'mode': 'METRO',
                'latitude': 23.2150,
                'longitude': 72.6390,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-GND-06',
                'name': 'Sector 10A / Sachivalaya',
                'name_gu': 'સેક્ટર ૧૦A / સચિવાલય',
                'name_hi': 'સેક્ટર 10A / सचिवालय',
                'code': 'SEC10',
                'city': 'GANDHINAGAR',
                'mode': 'METRO',
                'latitude': 23.2320,
                'longitude': 72.6480,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2 (Direct connection to Gujarat New Sachivalaya & Vidhan Sabha)',
            },
            {
                'stop_id': 'METRO-GND-08',
                'name': 'Sector 16 Metro',
                'name_gu': 'સેક્ટર ૧૬ મેટ્રો',
                'name_hi': 'सेक्टर 16 मेट्रो',
                'code': 'SEC16',
                'city': 'GANDHINAGAR',
                'mode': 'METRO',
                'latitude': 23.2450,
                'longitude': 72.6550,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-GND-09',
                'name': 'Sector 24 Metro',
                'name_gu': 'સેક્ટર ૨૪ મેટ્રો',
                'name_hi': 'सेक्टर 24 मेट्रो',
                'code': 'SEC24',
                'city': 'GANDHINAGAR',
                'mode': 'METRO',
                'latitude': 23.2550,
                'longitude': 72.6590,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-GND-07',
                'name': 'Mahatma Mandir Metro (Gandhinagar Capital)',
                'name_gu': 'મહાત્મા મંદિર મેટ્રો (ગાંધીનગર કેપિટલ)',
                'name_hi': 'महात्मा मंदिर मेट्रो (गांधीनगर कैपिटल)',
                'code': 'MMND',
                'city': 'GANDHINAGAR',
                'mode': 'METRO',
                'latitude': 23.2590,
                'longitude': 72.6520,
                'is_interchange': True,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2 (Terminal - 250m from Gandhinagar Capital Railway Station)',
            },

            # --- GIFT City Metro Branch (GNLU Interchange -> GIFT City FinTech Hub) ---
            {
                'stop_id': 'METRO-GIFT-01',
                'name': 'PDEU / PDPU (Pandit Deendayal Energy University)',
                'name_gu': 'પીડીઇયુ / પીડીપીયુ',
                'name_hi': 'पीडीईयू / पीडीपीयू',
                'code': 'PDEU',
                'city': 'GANDHINAGAR',
                'mode': 'METRO',
                'latitude': 23.1940,
                'longitude': 72.6600,
                'is_interchange': False,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2',
            },
            {
                'stop_id': 'METRO-GIFT-02',
                'name': 'GIFT City Metro Station',
                'name_gu': 'ગિફ્ટ સિટી મેટ્રો સ્ટેશન',
                'name_hi': 'गिफ्ट सिटी मेट्रो स्टेशन',
                'code': 'GIFT',
                'city': 'GIFT_CITY',
                'mode': 'METRO',
                'latitude': 23.1600,
                'longitude': 72.6840,
                'is_interchange': True,
                'wheelchair_accessible': True,
                'has_elevator': True,
                'has_escalator': True,
                'platform_info': 'Platform 1 & 2 (FinTech Hub / GIFT 1 & 2 Multi-Services Special Economic Zone)',
            },
        ]

    def get_routes(self) -> List[Dict[str, Any]]:
        return [
            {
                'route_id': 'GMRC-BLUE-EW',
                'route_number': 'Blue Line (East-West)',
                'route_name': 'Thaltej Gam ↔ Vastral Gam',
                'mode': 'METRO',
                'color': '#2563EB',
                'text_color': '#FFFFFF',
                'headway_peak_mins': 6,
                'headway_offpeak_mins': 12,
                'first_trip_time': '06:20',
                'last_trip_time': '22:00',
                'average_speed_kmh': 36.0,
                'reliability_score': 0.98,
            },
            {
                'route_id': 'GMRC-RED-NS',
                'route_number': 'Red Line (North-South)',
                'route_name': 'APMC ↔ Motera Stadium ↔ GNLU ↔ Mahatma Mandir',
                'mode': 'METRO',
                'color': '#DC2626',
                'text_color': '#FFFFFF',
                'headway_peak_mins': 6,
                'headway_offpeak_mins': 10,
                'first_trip_time': '06:20',
                'last_trip_time': '22:30',
                'average_speed_kmh': 38.0,
                'reliability_score': 0.98,
            },
            {
                'route_id': 'GMRC-GIFT-BR',
                'route_number': 'GIFT City Branch Line',
                'route_name': 'GNLU Interchange ↔ PDEU ↔ GIFT City FinTech Hub',
                'mode': 'METRO',
                'color': '#0891B2',
                'text_color': '#FFFFFF',
                'headway_peak_mins': 8,
                'headway_offpeak_mins': 15,
                'first_trip_time': '06:30',
                'last_trip_time': '22:15',
                'average_speed_kmh': 40.0,
                'reliability_score': 0.99,
            },
        ]

    def get_route_stops(self) -> List[Dict[str, Any]]:
        result = []

        # Blue Line: Thaltej Gam -> Vastral Gam
        blue_stops = [
            'METRO-EW-01', 'METRO-EW-02', 'METRO-EW-03', 'METRO-EW-04',
            'METRO-EW-05', 'METRO-EW-06', 'METRO-EW-07', 'METRO-INT-01',
            'METRO-EW-08', 'METRO-EW-09', 'METRO-EW-10', 'METRO-EW-11',
            'METRO-EW-12', 'METRO-EW-13', 'METRO-EW-14', 'METRO-EW-15',
            'METRO-EW-16', 'METRO-EW-17'
        ]
        cum_dist = 0.0
        for seq, sid in enumerate(blue_stops, start=1):
            result.append({
                'route_id': 'GMRC-BLUE-EW',
                'stop_id': sid,
                'sequence': seq,
                'distance_from_start_km': round(cum_dist, 2),
                'travel_time_mins': 2.0 if seq > 1 else 0.0,
                'is_major_stop': sid in ['METRO-EW-02', 'METRO-INT-01', 'METRO-EW-10', 'METRO-EW-11', 'METRO-EW-15'],
            })
            cum_dist += 1.4

        # Red Line: APMC -> Motera Stadium -> GNLU -> Mahatma Mandir
        red_stops = [
            'METRO-NS-14', 'METRO-NS-13', 'METRO-NS-12', 'METRO-NS-11',
            'METRO-NS-10', 'METRO-NS-09', 'METRO-NS-08', 'METRO-INT-01',
            'METRO-NS-07', 'METRO-NS-06', 'METRO-NS-05', 'METRO-NS-04',
            'METRO-NS-03', 'METRO-NS-02', 'METRO-NS-01',
            # Phase 2
            'METRO-NS-16', 'METRO-NS-17', 'METRO-NS-18', 'METRO-NS-19',
            'METRO-NS-20', 'METRO-NS-21', 'METRO-NS-22', 'METRO-INT-02',
            'METRO-GND-01', 'METRO-GND-02', 'METRO-GND-03', 'METRO-GND-04',
            'METRO-GND-05', 'METRO-GND-06', 'METRO-GND-08', 'METRO-GND-09', 'METRO-GND-07'
        ]
        cum_dist = 0.0
        for seq, sid in enumerate(red_stops, start=1):
            result.append({
                'route_id': 'GMRC-RED-NS',
                'stop_id': sid,
                'sequence': seq,
                'distance_from_start_km': round(cum_dist, 2),
                'travel_time_mins': 2.2 if seq > 1 else 0.0,
                'is_major_stop': sid in ['METRO-NS-14', 'METRO-INT-01', 'METRO-NS-02', 'METRO-NS-01', 'METRO-NS-18', 'METRO-INT-02', 'METRO-GND-04', 'METRO-GND-07'],
            })
            cum_dist += 1.5

        # GIFT City Branch: GNLU Interchange -> PDEU -> GIFT City
        gift_stops = ['METRO-INT-02', 'METRO-GIFT-01', 'METRO-GIFT-02']
        cum_dist = 0.0
        for seq, sid in enumerate(gift_stops, start=1):
            result.append({
                'route_id': 'GMRC-GIFT-BR',
                'stop_id': sid,
                'sequence': seq,
                'distance_from_start_km': round(cum_dist, 2),
                'travel_time_mins': 3.0 if seq > 1 else 0.0,
                'is_major_stop': True,
            })
            cum_dist += 2.8

        return result

    def get_transfers(self) -> List[Dict[str, Any]]:
        return [
            {
                'from_stop_id': 'METRO-INT-01',
                'to_stop_id': 'METRO-INT-01',
                'transfer_type': 'METRO_INTERCHANGE',
                'walking_distance_m': 60,
                'walking_time_mins': 2.0,
                'transfer_penalty_mins': 2.0,
                'instructions': 'Change platforms between Blue Line (Level 1) and Red Line (Level 2) via central concourse elevators or escalators.',
                'from_platform': 'Level 1 (Blue Line)',
                'to_platform': 'Level 2 (Red Line)',
                'stand_number': 'Platform 2/3',
                'transfer_buffer_mins': 3.0,
                'is_step_free': True,
            },
            {
                'from_stop_id': 'METRO-INT-02',
                'to_stop_id': 'METRO-INT-02',
                'transfer_type': 'METRO_INTERCHANGE',
                'walking_distance_m': 50,
                'walking_time_mins': 1.5,
                'transfer_penalty_mins': 2.0,
                'instructions': 'Step-free cross-platform concourse transfer between Red Line (Mahatma Mandir) and GIFT City Branch.',
                'from_platform': 'Platform 1 (Red Line)',
                'to_platform': 'Platform 3 (GIFT City Branch)',
                'stand_number': 'Platform 3',
                'transfer_buffer_mins': 2.5,
                'is_step_free': True,
            },
        ]

    def get_fare_rules(self) -> Dict[str, Any]:
        return {
            'agency_code': 'GMRC',
            'mode': 'METRO',
            'base_fare': 5.0,
            'base_distance_km': 2.5,
            'per_km_rate': 1.1,
            'max_fare': 35.0,
            'fare_brackets': [
                {'km': 2.5, 'fare': 5},
                {'km': 7.5, 'fare': 10},
                {'km': 12.5, 'fare': 15},
                {'km': 17.5, 'fare': 20},
                {'km': 25.0, 'fare': 25},
                {'km': 35.0, 'fare': 30},
                {'km': 99.0, 'fare': 35},
            ]
        }

    def get_vehicles(self) -> List[Dict[str, Any]]:
        return [
            {
                'vehicle_id': 'METRO-TR-EW01',
                'registration': 'GMRC-TS-301',
                'mode': 'METRO',
                'route_id': 'GMRC-BLUE-EW',
                'capacity': 950,
                'is_electric': True,
                'latitude': 23.0401,
                'longitude': 72.5709,
                'speed_kmh': 42.0,
                'current_location_name': 'Old High Court Concourse',
                'next_stop_id': 'METRO-EW-07',
                'delay_minutes': 0,
                'status': 'ON_TIME',
            },
            {
                'vehicle_id': 'METRO-TR-NS02',
                'registration': 'GMRC-TS-304',
                'mode': 'METRO',
                'route_id': 'GMRC-RED-NS',
                'capacity': 950,
                'is_electric': True,
                'latitude': 23.0762,
                'longitude': 72.5855,
                'speed_kmh': 38.0,
                'current_location_name': 'Sabarmati Metro Platform 1',
                'next_stop_id': 'METRO-NS-03',
                'delay_minutes': 0,
                'status': 'ON_TIME',
            },
            {
                'vehicle_id': 'METRO-TR-GND01',
                'registration': 'GMRC-TS-312',
                'mode': 'METRO',
                'route_id': 'GMRC-RED-NS',
                'capacity': 950,
                'is_electric': True,
                'latitude': 23.1900,
                'longitude': 72.6320,
                'speed_kmh': 45.0,
                'current_location_name': 'GNLU Interchange Approaching Platform 2',
                'next_stop_id': 'METRO-GND-01',
                'delay_minutes': 0,
                'status': 'ON_TIME',
            },
            {
                'vehicle_id': 'METRO-TR-GIFT01',
                'registration': 'GMRC-TS-318',
                'mode': 'METRO',
                'route_id': 'GMRC-GIFT-BR',
                'capacity': 600,
                'is_electric': True,
                'latitude': 23.1770,
                'longitude': 72.6720,
                'speed_kmh': 48.0,
                'current_location_name': 'Approaching GIFT City Multi-Services SEZ',
                'next_stop_id': 'METRO-GIFT-02',
                'delay_minutes': 0,
                'status': 'ON_TIME',
            }
        ]

    def get_service_alerts(self) -> List[Dict[str, Any]]:
        return [
            {
                'title': 'GMRC Metro Operating Normally Across All Corridors',
                'description': 'Ahmedabad ↔ Gandhinagar Metro and GIFT City Branch trains are operating at standard 6-8 minute headway.',
                'severity': 'INFO',
                'status': 'ACTIVE',
                'delay_impact_mins': 0,
            }
        ]
