# Generated by Django 6.1.1 on 2026-09-08 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('latitude', models.FloatField(default=23.0225)),
                ('longitude', models.FloatField(default=72.5714)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('vehicle_count', models.IntegerField(default=0)),
                ('car_count', models.IntegerField(default=0)),
                ('bus_count', models.IntegerField(default=0)),
                ('truck_count', models.IntegerField(default=0)),
                ('two_wheeler_count', models.IntegerField(default=0)),
                ('auto_count', models.IntegerField(default=0)),
                ('average_speed', models.FloatField(default=35.0, help_text='Average speed in km/h')),
                ('congestion_level', models.CharField(choices=[('LOW', 'Low / Free Flow'), ('MODERATE', 'Moderate Flow'), ('HEAVY', 'Heavy Congestion'), ('SEVERE', 'Severe Gridlock')], default='MODERATE', max_length=20)),
                ('congestion_index', models.IntegerField(default=50, help_text='Score 0 (free) to 100 (gridlock)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_observations', to='fleet.bus')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['location', '-timestamp'], name='traffic_tra_locatio_616dcb_idx'), models.Index(fields=['-timestamp'], name='traffic_tra_timesta_7dedb5_idx')],
            },
        ),
    ]
